name: lupi
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pytorch
  - torchvision
  - cudatoolkit
  - pip
  - pip:
      - pillow==10.4.0
      - tensorflow==2.13.0
      - jupyter==1.0.0
      - pandas==2.2.2
      - matplotlib==3.9.1
      - scikit-learn==1.5.1
      - tqdm
      - wandb
